joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      fer_joint1: {p: 600., d: 30., i: 0.2, i_clamp: 2.0, ff_velocity_scale: 0.75}
      fer_joint2: {p: 600., d: 30., i: 0.2, i_clamp: 2.0, ff_velocity_scale: 0.75}
      fer_joint3: {p: 600., d: 30., i: 0.2, i_clamp: 2.0, ff_velocity_scale: 0.75}
      fer_joint4: {p: 600., d: 30., i: 0.2, i_clamp: 2.0, ff_velocity_scale: 0.75}
      fer_joint5: {p: 200., d: 3., i: 0.8, i_clamp: 4.0, ff_velocity_scale: 0.75}
      fer_joint6: {p: 80., d: 1., i: 0.8, i_clamp: 5.0, ff_velocity_scale: 0.75}
      fer_joint7: {p: 80., d: 1., i: 0.8, i_clamp: 5.0, ff_velocity_scale: 0.75}
