joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      fer_joint1: {p: 200., d: 10., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint2: {p: 200., d: 10., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint3: {p: 200., d: 10., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint4: {p: 200., d: 10., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint5: {p: 100., d: 5., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint6: {p: 50., d: 5., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
      fer_joint7: {p: 20., d: 2., i: 0.01, i_clamp: 0.1, ff_velocity_scale: 0.75}
    # constraints:
    #   fer_joint1: {goal: 0.01}
    #   fer_joint2: {goal: 0.01}
    #   fer_joint3: {goal: 0.01}
    #   fer_joint4: {goal: 0.01}
    #   fer_joint5: {goal: 0.01}
    #   fer_joint6: {goal: 0.01}
    #   fer_joint7: {goal: 0.01}
