/**:
  ros__parameters:
    moving_joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    poses_to_reach_names:
      - down
      - up
    down:
      xyz: [0.3, 0.0, 0.5]
      quat: [0.923, -0.382, 0.0, 0.0]
    up:
      xyz: [0.3, 0.0, 0.4]
      quat: [0.923, -0.382, 0.0, 0.0]
    configuration_tolerance_pose: 0.01
    configuration_tolerance_rot: 0.05
    tcp_frame_id: fer_link8
    base_frame_id: fer_link0
    settle_time: 2.0
    controller_frequency: 50.0
    n_trajectory_points: 5
    max_angular_velocity: 3.14
